hostname = *.igetget.com,*.music.163.com


https://.*\.igetget\.com.* url script-request-header https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tdd9.js


https://.*\.music\.163\.com.*  url script-request-header https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/twy.js