hostname = *.music.163.com


# WeChat Mini Program Ad Blocking Rules Reference
^https?:\/\/.*\.qq\.com.*(ad|ADS|advertise) url reject-force-body
^https?:\/\/.*\.tencent\.com.*(ad|ADS|advertise) url reject-force-body
^https?:\/\/ads\.wechat\.com url reject
^https?:\/\/mobileads\.qzone\.qq\.com url reject

https://.*\.music\.163\.com.*  url script-request-header https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/twy.js

^https?:\/\/.*\/api\/clientlog\/encrypt\/upload url reject-array
^https?:\/\/.*\/eapi\/ad\/.+ url reject-array
