hostname = hytapiv2.cd120.com



https://hytapiv2.cd120.com/cloud/hosplatcustomer/call/appointment/selDoctorDetailsTwo url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/testhx.js
