# 京东
#浏览器登录 https://bean.m.jd.com 点击签到并且出现签到日历
1,3 0 * * * https://gitlab.com/conflict1203/QuantumultX/-/raw/master/NobyDa/JD-DailyBonus/JD_DailyBonus.js, tag=京东, img-url=https://gitlab.com/conflict1203/QuantumultX/-/raw/master/Orz-3/task/master/jd.png,enabled=true



# 网易云音乐
#1. 先登录: <https://music.163.com/m/login>
#2. 再访问: <https://music.163.com/#/user/level>
#3. 提示: `获取会话: 成功!`
3 0 * * * https://gitlab.com/conflict1203/QuantumultX/-/raw/master/chavyleung/neteasemusic/quanx/neteasemusic.js, tag=网易云音乐, img-url=https://gitlab.com/conflict1203/QuantumultX/-/raw/master/Orz-3/task/master/Netease.png,enabled=true


# 什么值得买
#浏览器访问并登录: https://zhiyou.smzdm.com/user/login
5 0 * * * https://gitlab.com/conflict1203/QuantumultX/-/raw/master/chavyleung/smzdm/quanx/smzdm.js, tag=什么值得买, img-url=https://gitlab.com/conflict1203/QuantumultX/-/raw/master/Orz-3/task/master/smzdm.png,enabled=true

# 喜马拉雅
#打开 APP, 访问下右下角`账号`
6 0 * * * https://gitlab.com/conflict1203/QuantumultX/-/raw/master/chavyleung/ximalaya/ximalaya.js, tag=喜马拉雅, img-url=https://gitlab.com/conflict1203/QuantumultX/-/raw/master/Orz-3/task/master/ximalaya.png,enabled=true


# 叮咚买菜
#打开 APP, 访问下`我的`>`积分`
10 0 * * * https://gitlab.com/conflict1203/QuantumultX/-/raw/master/chavyleung/mcdd/mcdd.js, tag=叮咚买菜, img-url=https://gitlab.com/conflict1203/QuantumultX/-/raw/master/Orz-3/task/master/mcdd.png,enabled=true


# 不背单词
# 打开App,然后手动签1次
13 0 * * * https://gitlab.com/conflict1203/QuantumultX/-/raw/master/chavyleung/bubei/bubei.js, tag=不背单词, img-url=https://gitlab.com/conflict1203/QuantumultX/-/raw/master/Orz-3/task/master/bubei.png,enabled=true


# > 百果园
# 进入小程序直接签到
10 0 * * * https://gitlab.com/conflict1203/QuantumultX/-/raw/master/chavyleung/pagoda/pagoda.js, tag=百果园, img-url=https://gitlab.com/conflict1203/QuantumultX/-/raw/master/Orz-3/task/master/pagoda.png, enabled=true








