
hostname = flomoapp.com,*.bilibili.com,api.revenuecat.com,api.termius.com,ec.myjkyd.com,cn.invit.vip,menscoach-api.asqq.io


https:\/\/flomoapp\.com\/api\/v1\/user\/me url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tt.js


https:\/\/flomoapp\.com\/api\/v1\/pro\/apple url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tt.js



^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\? url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tbill.js


https:\/\/api\.revenuecat\.com\.* url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tgrow.js

https:\/\/api\.termius\.com\/api\/v3\/bulk\/account\/ url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/termus.js


# 
http:\/\/ec\.myjkyd\.com\/ftec url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tjkyd.js


^https:\/\/cn\.invit\.vip\/users\/info url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tdzqj.js

^https:\/\/menscoach-api\.asqq\.io\/prod\/user$ url script-response-body https://raw.githubusercontent.com/GN006/QuantumultX/master/langkhach/MuscleBooster.js
