hostname = api.gotokeep.com,59.110.149.231,129.211.156.213

https://api.gotokeep.com/(.+/subject|.+/dynamic|.+/coursePlus/.+|.+/status|.+/tab|.+/my|.+/start|.+/join|.+/complete|.+/detail/.+|.+/preview|.+/auth|.+/tab|.+/days) url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tkeep.js