
hostname = flomoapp.com,api.xunyou.mobi


https:\/\/flomoapp\.com\/api\/v1\/user\/me url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tt.js


https:\/\/flomoapp\.com\/api\/v1\/pro\/apple url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tt.js


https://flomoapp.com/api/v1/memo/notify_of_today/.* url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/tt-mac.js

^https:\/\/api\.xunyou\.mobi\/api\/v1\/android\/sessions url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/xyjsq.js