
hostname = hxgyapiv2.cd120.info

https://hxgyapiv2.cd120.info/cloud/hosplatcustomer/usercenter/account/login url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/thx.js

