
hostname = hxgyapiv2.cd120.info

https://hxgyapiv2.cd120.info/cloud/hosplatcustomer/usercenter/account/login url script-request-body https://raw.githubusercontent.com/conflict1203-sketch/yeah/refs/heads/master/tt/thx.js


https://hxgyapiv2.cd120.info/cloud/hosplatcustomer/usercenter/account/device/change url script-request-body https://raw.githubusercontent.com/conflict1203-sketch/yeah/refs/heads/master/tt/thx2.js
