
########################################
# 游戏服务器域名
########################################
hostname = api01.mihuangame.com

########################################
# 屏蔽广告请求
########################################

^https?:\/\/api01\.mihuangame\.com\/api\/v\d\/sys\/user\/login url script-response-body https://gitlab.com/conflict1203/QuantumultX/-/raw/master/tt/zhaoyu-tl.js
