
########################################
# 游戏服务器域名
########################################
hostname = api01.mihuangame.com

########################################
# 屏蔽广告请求
########################################

^https?:\/\/api01\.mihuangame\.com\/api\/v\d\/sys\/user\/login url script-response-body https://raw.githubusercontent.com/conflict1203-sketch/yeah/refs/heads/master/tt/zhaoyu-tl.js
