
########################################
# 游戏服务器域名
########################################
hostname = api01.mihuangame.com

########################################
# 屏蔽广告请求
########################################

# > 屏蔽广告数据上报接口（游戏结束时的奖励统计）
^https?:\/\/api01\.mihuangame\.com\/api\/v\d\/zyyad\/(ad|advertisement|reward).* url reject-200

# > 屏蔽积分添加接口（观看广告获得的积分）
^https?:\/\/api01\.mihuangame\.com\/api\/v\d\/sys\/oa\/point\/add url reject-200

# > 屏蔽广告展示追踪
^https?:\/\/api01\.mihuangame\.com\/api\/v\d\/.*\/(show|view|click) url reject-200

# > 屏蔽激励视频广告回调
^https?:\/\/api01\.mihuangame\.com\/api\/v\d\/.*\/video\/callback url reject-200


# 如果 win 参数在 URL 中，可以直接替换
^https?:\/\/api01\.mihuangame\.com\/api\/v\d\/zyyad\/game\/end\?(.*&)?win=\d+(&.*)?$ request-header-replace win=\d+ win=1
